<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="vecteezy_aircraft-wing-and-clouds-at-sunset_1963903.jpg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjetFinal.Core\ProjetFinal.Core.csproj" />
    <ProjectReference Include="..\ProjetFinal.Data\ProjetFinal.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="vecteezy_aircraft-wing-and-clouds-at-sunset_1963903.jpg" />
  </ItemGroup>

</Project>
